/*
 * generated by Xtext 2.15.0
 */
package de.fzi.emfcompare.matching


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MatchesStandaloneSetup extends MatchesStandaloneSetupGenerated {

	def static void doSetup() {
		new MatchesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
