/*
 * generated by Xtext 2.15.0
 */
package de.fzi.emfcompare.matching


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MatchesRuntimeModule extends AbstractMatchesRuntimeModule {
}
