/*
 * generated by Xtext 2.15.0
 */
package de.fzi.emfcompare.matching.tests

import com.google.inject.Inject
import de.fzi.emfcompare.matching.matches.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@InjectWith(MatchesInjectorProvider)
@RunWith(XtextRunner)
class MatchesParsingTest {
	
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Compare
			left: "leftFileString"
			right: "rightFileString"
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
	
	@Test
	def void loadModelNoResources() {
		val result = parseHelper.parse('''
			Compare
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
